<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="W1650916" name="Training.NewTest" tests="5" failures="1" timestamp="03 Oct 2017 06:10:11 GMT" time="0.032" errors="0">
  <testcase name="f" time="0.025" classname="Training.NewTest"/>
  <testcase name="g" time="0.001" classname="Training.NewTest"/>
  <testcase name="h" time="0.001" classname="Training.NewTest"/>
  <testcase name="i" time="0.003" classname="Training.NewTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	1st assert failed.f expected [Tuesday23, 01 January 2014] but found [Tuesday, 01 January 2014],
	presentf expected [true] but found [false],
	1st assert failed. expected [Tuesday23, 01 January 2014] but found [Tuesday, 01 January 2014],
	present expected [true] but found [false],
	1st assert failed. expected [Tuesday23, 01 January 2014] but found [Tuesday, 01 January 2014],
	present expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	1st assert failed.f expected [Tuesday23, 01 January 2014] but found [Tuesday, 01 January 2014],
	presentf expected [true] but found [false],
	1st assert failed. expected [Tuesday23, 01 January 2014] but found [Tuesday, 01 January 2014],
	present expected [true] but found [false],
	1st assert failed. expected [Tuesday23, 01 January 2014] but found [Tuesday, 01 January 2014],
	present expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Training.NewTest.i(NewTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- i -->
  <testcase name="j" time="0.002" classname="Training.NewTest"/>
</testsuite> <!-- Training.NewTest -->
